### PR TITLE
Add projects export for retro 

### PR DESCRIPTION
**Pull request by tilenseer**
Add possibility to export projects for the retro branch

### CODE REVIEW

**Comment by jensstalder** [comment]
At some point we will need to retire this retro branch.

**Comment by jensstalder** [comment]
@tilenseer This is mergeable right? Don't worry about the travis ci error. This is old.

**Comment by jensstalder** [comment]
Screenshot 2021-05-19 at 08 51 52

@tilenseer  checked some random xml with the schema and it is valid. I will merge once you give me the ok.

**Comment by tilenseer** [comment]
@jensstalder Yes, you can merge it. The local lint does also works fine.

**Pull request merged**
